ALTER TABLE "Invoice" ADD COLUMN IF NOT EXISTS "invoiceType"     TEXT NOT NULL DEFAULT 'REGULAR';
ALTER TABLE "Invoice" ADD COLUMN IF NOT EXISTS "driverName"      TEXT;
ALTER TABLE "Invoice" ADD COLUMN IF NOT EXISTS "departureTime"   TIMESTAMP;
ALTER TABLE "Invoice" ADD COLUMN IF NOT EXISTS "confirmedAt"     TIMESTAMP;
ALTER TABLE "Invoice" ADD COLUMN IF NOT EXISTS "confirmedByName" TEXT;
